blank_issues_enabled: false
contact_links:
  - name: 💬 Soporte General
    url: https://github.com/dancascol/miPrimerRepo/discussions
    about: Si tu consulta no es un bug ni una feature, abre una discusión aquí.
